# ==============================================================================
# GITLEAKS CONFIGURATION - ENTERPRISE AWS 3-TIER ARCHITECTURE
# ==============================================================================
# Custom configuration to allow example credentials in documentation
# while still scanning for real secrets
# ==============================================================================

title = "Gitleaks Configuration for Portfolio Project"

[allowlist]
description = "Allowlist for example credentials and documentation"

# Allow example AWS credentials used in documentation
regexes = [
  '''AKIAIOSFODNN7EXAMPLE''',
  '''wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY''',
  '''example\.com''',
  '''your-.*''',
  '''YOUR_.*'''
]

# Exclude documentation and example files
paths = [
  '''docs/.*''',
  '''.*\.md$''',
  '''examples/.*''',
  '''.github/.*'''
]
