---
# ==============================================================================
# SECURITY SCANNING WORKFLOW - ENTERPRISE AWS 3-TIER ARCHITECTURE
# ==============================================================================
# This workflow runs security scans for both frontend and backend applications
# Zero-cost mode: All scans run locally, no external dependencies
# Manual trigger only for portfolio demonstration
# ==============================================================================

name: Security Scan

on:
  workflow_dispatch:

jobs:
  security-scan:
    name: Run Security Scans
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: |
          cd frontend
          npm install
          cd ../backend
          npm install

      - name: Run npm audit (frontend)
        continue-on-error: true
        run: |
          cd frontend
          npm audit --audit-level=moderate || true

      - name: Run npm audit (backend)
        continue-on-error: true
        run: |
          cd backend
          npm audit --audit-level=moderate || true

      - name: Run Gitleaks
        uses: zricethezav/gitleaks-action@v2
        with:
          config: .gitleaks.toml
