# ==============================================================================
# TERRAFORM VALIDATION WORKFLOW - ENTERPRISE AWS 3-TIER ARCHITECTURE
# ==============================================================================
# This workflow validates Terraform code for syntax, security, and best practices
# Runs automatically on pull requests and main branch pushes for Terraform changes
# ==============================================================================

name: Terraform Validation

on:
  pull_request:
    paths:
      - 'terraform/**'
      - '.github/workflows/terraform-validation.yml'
  push:
    branches: [ main ]

jobs:
  terraform-validation:
    name: Terraform Validate and Security Scan
    runs-on: ubuntu-latest
    
    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Setup Terraform with pinned version
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0

    # Validate Terraform code formatting
    - name: Terraform Format Check
      id: fmt
      run: |
        terraform fmt -check -recursive terraform/
        echo "Format check completed"

    # Initialize Terraform without backend for validation
    - name: Terraform Init
      id: init
      run: |
        cd terraform/environments/production
        terraform init -backend=false
        echo "Terraform init completed"

    # Validate Terraform syntax and configuration
    - name: Terraform Validate
      id: validate
      run: |
        cd terraform/environments/production
        terraform validate
        echo "Terraform validate completed"

    # Create execution plan for review
    - name: Terraform Plan
      id: plan
      run: |
        cd terraform/environments/production
        terraform plan -lock=false -input=false
        echo "Terraform plan completed"

    # Security scanning for Terraform code
    - name: Terraform Security Scan
      id: tfsec
      uses: aquasecurity/tfsec-action@v1.0.0
      with:
        directory: terraform/

    # Upload plan artifact for manual review
    - name: Upload Plan Artifact
      uses: actions/upload-artifact@v3
      with:
        name: terraform-plan
        path: |
          terraform/environments/production
        if-no-files-found: ignore